project_id = "hdoaljpejropkjhazqxp"

[functions.generate-lyrics]
verify_jwt = false

[functions.generate-song]
verify_jwt = false

[functions.kie-callback]
verify_jwt = false

[functions.check-task]
verify_jwt = false
