project_id = "hdoaljpejropkjhazqxp"

[functions.generate-lyrics]
verify_jwt = false

[functions.generate-lyrics-only]
verify_jwt = false

[functions.generate-song]
verify_jwt = false

[functions.kie-callback]
verify_jwt = false

[functions.check-task]
verify_jwt = false

[functions.get-my-songs]
verify_jwt = false

[functions.start-music-after-payment]
verify_jwt = false

[functions.generate-video-images]
verify_jwt = false

[functions.send-download-email]
verify_jwt = false
